// Generate anime poster images using AI
const fs = require('fs');
const path = require('path');

// All unique anime titles from animeData.js
const animeList = [
    "Attack on Titan",
    "My Hero Academia",
    "Demon Slayer",
    "Tokyo Ghoul",
    "Jujutsu Kaisen",
    "One Piece",
    "Naruto",
    "Naruto Shippuden",
    "Fullmetal Alchemist: Brotherhood",
    "Death Note",
    "Steins;Gate",
    "Steins;Gate 0",
    "Hunter x Hunter",
    "Sword Art Online",
    "Code Geass",
    "Cowboy Bebop",
    "Mob Psycho 100",
    "One Punch Man",
    "Bleach",
    "Bleach: Thousand-Year Blood War",
    "Dragon Ball Z",
    "Dragon Ball Super",
    "Vinland Saga",
    "Re:Zero",
    "The Promised Neverland",
    "Solo Leveling",
    "Frieren: Beyond Journey's End",
    "Chainsaw Man",
    "Spy x Family",
    "Mushoku Tensei",
    "Overlord",
    "That Time I Got Reincarnated as a Slime",
    "Konosuba",
    "Violet Evergarden",
    "Your Lie in April",
    "Toradora!",
    "Parasyte",
    "Anohana",
    "Clannad",
    "Clannad: After Story",
    "Kaguya-sama: Love is War",
    "Horimiya",
    "Fruits Basket",
    "Erased",
    "Made in Abyss",
    "Dr. Stone",
    "The Rising of the Shield Hero",
    "Assassination Classroom",
    "Noragami",
    "Blue Exorcist",
    "Black Clover",
    "Fire Force",
    "Dororo",
    "Beastars"
];

console.log('Anime list to generate:');
console.log(JSON.stringify(animeList, null, 2));
console.log(`\nTotal: ${animeList.length} unique anime titles`);
